sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: c3eno+hD/LcxQUBVdd0MHeHEaYaXAqLzo9Cx5FXhI5Dag5SxN4ZeqY+PkhuUWjfBdsIAKBimKlwMDhaUAkf/svtw6QtNdwYoQAFSQBgvffyQSy6iNucmOkU3COWLOejdiy6zL0BzpeX0VxNJrApaYaCoqdNAXM4MUsFOQQPTHCnsooLeRA4m0Tk7Q4KMgYP8wjBFRcYjaBe2Zead2aGSigXo1xoXBxywbDi5zH1KythqxAoDOzkicfcgmSSWnpx1YggRYvfqJErsUmxFhib/9zarJ77DQAnct/K09tCkH+GjfbfT2wd11tat/XIqwkCHlwpMhkgUrQdA+sFq04UOQZAvoqObsZwTXRr+tucxNzW51dBKRZQy9EE7uD4yMnw73WTe1K0LClto0pdzGDVI0UARPTBkce91TaVgTYywPQkgMYjXkhQANiRRW/YuVjRtqB2+8z7Kq5QjHhVs8g+eKZ/gTm9t+tABON26U75Pg0IxeWipNTJ8KtMXpg1efxmXm24m1ZVnq8vD+bcxxmllflEKp+de96fxueoIooC5tnogae4Vejy25VdQBWvBRpnBoCw1ROxDCcGv6imYctIFn4Vr+FFPQ+PtOfuxFrAr2saN3w56c1mCnYECAIaZPgFtPNowdYRwVU7i7UXYUhLZDtnwFh43mQPfioPdl01wHJQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Business-Hints-for-Men-and-Women_6167
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy